spring.application.name=food-rescue-backend

spring.datasource.url=jdbc:mysql://junction.proxy.rlwy.net:10835/railway
spring.datasource.username=root
spring.datasource.password=tVetRmHYvsBLaOaLmGekOtRfngkfVuor

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}